# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-22 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_reg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='password',
            field=models.TextField(default='NOT_PROVIDED'),
        ),
    ]
